### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by mleppanen** [Zen3515/homeassistant-vyos-router#3]
Hi,

I just installed the component, and have it now communicating, to some degree, with the router. The router is in this case 192.168.86.111 and the port is 443
How ever, it is now repeating the following:
```
`2024-01-23 15:55:43.260 ERROR (MainThread) [custom_components.vyos.router] Unexpected error fetching VyOS - https://192.168.86.111:443 data: <ClientResponse(https://192.168.86.111:443/retrieve) [400 Bad Request]>
<CIMultiDictProxy('Server': 'nginx/1.22.1', 'Date': 'Tue, 23 Jan 2024 13:55:43 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '90', 'Connection': 'keep-alive')>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/vyos/router.py", line 203, in _async_update_data
await self.vyos_data.update_devices()
File "/config/custom_components/vyos/router.py", line 134, in update_devices
await static_mapping_co_routine
File "/config/custom_components/vyos/vyosapi.py", line 316, in get_config
raise VyOSApiError(res)
custom_components.vyos.vyosapi.VyOSApiError: <ClientResponse(https://192.168.86.111:443/retrieve) [400 Bad Request]>
<CIMultiDictProxy('Server': 'nginx/1.22.1', 'Date': 'Tue, 23 Jan 2024 13:55:43 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '90', 'Connection': 'keep-alive')>
2024-01-23 15:56:00.925 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py:423: RuntimeWarning: coroutine 'VyOSApi.get_dhcp_lease' was never awaited
self.headers: CIMultiDict[str] = CIMultiDict()
2024-01-23 15:56:00.926 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py:423: RuntimeWarning: coroutine 'VyOSApi.get_present_arp_clients' was never awaited
self.headers: CIMultiDict[str] = CIMultiDict()
2024-01-23 15:57:05.199 ERROR (MainThread) [custom_components.vyos.router] Unexpected error fetching VyOS - https://192.168.86.111:443 data: <ClientResponse(https://192.168.86.111:443/retrieve) [400 Bad Request]>
<CIMultiDictProxy('Server': 'nginx/1.22.1', 'Date': 'Tue, 23 Jan 2024 13:57:05 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '90', 'Connection': 'keep-alive')>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/vyos/router.py", line 203, in _async_update_data
await self.vyos_data.update_devices()
File "/config/custom_components/vyos/router.py", line 134, in update_devices
await static_mapping_co_routine
File "/config/custom_components/vyos/vyosapi.py", line 316, in get_config
raise VyOSApiError(res)
custom_components.vyos.vyosapi.VyOSApiError: <ClientResponse(https://192.168.86.111:443/retrieve) [400 Bad Request]>
<CIMultiDictProxy('Server': 'nginx/1.22.1', 'Date': 'Tue, 23 Jan 2024 13:57:05 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '90', 'Connection': 'keep-alive')>
2024-01-23 15:58:08.160 WARNING (Recorder) [py.warnings] <string>:21: RuntimeWarning: coroutine 'VyOSApi.get_dhcp_lease' was never awaited
2024-01-23 15:58:08.161 WARNING (Recorder) [py.warnings] <string>:21: RuntimeWarning: coroutine 'VyOSApi.get_present_arp_clients' was never awaited
2024-01-23 15:58:27.130 ERROR (MainThread) [custom_components.vyos.router] Unexpected error fetching VyOS - https://192.168.86.111:443 data: <ClientResponse(https://192.168.86.111:443/retrieve) [400 Bad Request]>
<CIMultiDictProxy('Server': 'nginx/1.22.1', 'Date': 'Tue, 23 Jan 2024 13:58:27 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '90', 'Connection': 'keep-alive')>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/vyos/router.py", line 203, in _async_update_data
await self.vyos_data.update_devices()
File "/config/custom_components/vyos/router.py", line 134, in update_devices
await static_mapping_co_routine
File "/config/custom_components/vyos/vyosapi.py", line 316, in get_config
raise VyOSApiError(res)
custom_components.vyos.vyosapi.VyOSApiError: <ClientResponse(https://192.168.86.111:443/retrieve) [400 Bad Request]>
<CIMultiDictProxy('Server': 'nginx/1.22.1', 'Date': 'Tue, 23 Jan 2024 13:58:27 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '90', 'Connection': 'keep-alive')>
2024-01-23 15:58:28.425 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.11/asyncio/base_events.py:436: RuntimeWarning: coroutine 'VyOSApi.get_dhcp_lease' was never awaited
task = tasks.Task(coro, loop=self, name=name, context=context)
2024-01-23 15:58:28.425 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.11/asyncio/base_events.py:436: RuntimeWarning: coroutine 'VyOSApi.get_present_arp_clients' was never awaited
task = tasks.Task(coro, loop=self, name=name, context=context)
```

**Comment by Zen3515** [comment]
Hello,

Could you give me a little more info on which version of integration you're using, the home assistant version, and the vyos version?

In any case, it seems that installing an earlier version of this integration might be necessary. The latest version [2024.1.1](https://github.com/Zen3515/homeassistant-vyos-router/releases/tag/2024.1.1) is designed for VyOS version `1.5-rolling-202312290919` and later.

If you're installing through HACS, consider trying the older version [2022.8.1](https://github.com/Zen3515/homeassistant-vyos-router/releases/tag/2022.8.1)

**Comment by mleppanen** [comment]
Hi,

the component was installed through HACS today. HA is as follows:
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0
My Vyos is 1.4.-rc3 so that might explain.  I will try to downgrade.

**Comment by Zen3515** [comment]
I've pondered this, and even if you're required to utilize the older version of the integration, that doesn't clarify the issue in your situation.

For debugging reasons, could you attempt invoking the API directly with this command and omit any confidential information?

```bash
curl -v -k --location --request POST 'https://192.168.86.111:443/retrieve' --form data='{"op": "showConfig", "path": ["service", "dhcp-server", "shared-network-name"]}' --form key='MY-HTTPS-API-PLAINTEXT-KEY'
```

**Comment by mleppanen** [comment]
I suppose I managed to downgrade, at least the manifest.json is now stating 2022.8.1. Still the same(?) problem though. At least saying it's a bad request. Below the API dump.

```
`curl -v -k --location --request POST 'https://192.168.86.111:443/retrieve' --form data='{"op": "showConfig", "path": ["service", "dhcp-server", "shared-network-name"]}' --form key='MY-HTTPS-API-PLAINTEXT-KEY'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.86.111:443...
* Connected to 192.168.86.111 (192.168.86.111) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=localhost
*  start date: Jan  3 21:09:18 2024 GMT
*  expire date: Dec 31 21:09:18 2033 GMT
*  issuer: CN=localhost
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* using HTTP/1.1
> POST /retrieve HTTP/1.1
> Host: 192.168.86.111
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Length: 320
> Content-Type: multipart/form-data; boundary=------------------------74701d8cead5feb6
> 
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 400 Bad Request
< Server: nginx/1.22.1
< Date: Tue, 23 Jan 2024 15:23:47 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 90
< Connection: keep-alive
< 
* Connection #0 to host 192.168.86.111 left intact
{"success": false, "error": "Configuration under specified path is empty\n", "data":`
```

**Comment by Zen3515** [comment]
I understand now.

The problem stems from the vyos instance not functioning as the DHCP server. This integration relies on data from three origins:
- The `static-mapping` definded in `service dhcp-server shared-network-name XXX subnet XXX.XXX.XXX.XXX/XX static-mapping ...`
- DHCP leases at obtained from `show dhcp server leases state all`
- ARP information from `show arp`

It didn't occur to me that someone might employ this integration without configuring it as a DHCP server. I can work on a fix soon, but could you please share your specific use case?

**Comment by mleppanen** [comment]
Ah, yes. I am making a fresh install here, so I forgot that I am not yet using the router as the DHCP server and haven't enabled it to make sure my configuration works with a static setup first.  So, no real use case for that. Just setting things up one place at a time.

**Comment by Zen3515** [comment]
I regard this matter as resolved, as there are currently no intentions to implement a device tracker based solely on ARP

However @mleppanen with the latest release version 2024.1.2, you can now always install the latest version of this integration, ensuring that you have access to all the latest features.

If there arias a need for a device tracker based solely on ARP, please create a new issue for it.
